from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATASET_DIR = PROJECT_ROOT / "dataset"

LINE_IMAGE_DIR = DATASET_DIR / "segmentation_final"
LABEL_CSV = DATASET_DIR / "label_data.csv"
LINES_CLEAN_DIR = LINE_IMAGE_DIR
REVIEW_CSV = LABEL_CSV
TRAIN_CSV = LABEL_CSV
VAL_CSV = LABEL_CSV
TEST_CSV = LABEL_CSV

TROCR_DIR = PROJECT_ROOT / "trocr"
BASE_MODEL_NAME = str(TROCR_DIR / "notescan_trocr")
OUTPUT_DIR = TROCR_DIR / "trocr_model"
SAVE_DIR = TROCR_DIR / "notescan_trocr"

MAX_TARGET_LENGTH = 160
MAX_IMAGE_HEIGHT = 128
MAX_LABEL_CHARS = 150
NUM_BEAMS = 1
VAL_FRACTION = 0.1
TEST_FRACTION = 0.0

PER_DEVICE_TRAIN_BATCH_SIZE = 1
PER_DEVICE_EVAL_BATCH_SIZE = 1
GRADIENT_ACCUMULATION_STEPS = 8
LEARNING_RATE = 3e-5
NUM_TRAIN_EPOCHS = 20
LOGGING_STEPS = 10
EVAL_STEPS = 50
SAVE_STEPS = 50
SMOKE_LIMIT = 2
SMOKE_MAX_STEPS = 5
SEED = 42
